shared: Adds generic HasKey
lxc/lxd pull request #10125
Opened 2022-03-25 16:53 UTC by tomponline

Based on discussion https://github.com/lxc/lxd/pull/10115#discussion_r834708023

2022-03-25 21:05 UTC, stgraber commented
Mark as blocked as we'll have some other changes to make prior to being able to land a PR which restricts us to Go 1.18.

2022-03-25 21:32 UTC, tomponline commented
Makes sense, thanks.

2022-03-25 23:18 UTC, stgraber commented
So one issue I have with the 1.18 base change is that it will also impact every downstream of LXD as it's not going to just affect the daemon but the client package too. This may not be a problem as those folks may be able to pick the stable-4.0 branch to avoid running into this issue, but we should expect a fair amount of issues to result from the change, more than anticipated.

2022-03-25 23:19 UTC, tomponline commented
We can certainly move this in the server-side validation package if that helps?

2022-03-26 00:12 UTC, tomponline commented
@stgraber although the go mod version would still need to be at 1.18, so I guess we'll need to keep our min version at go 1.17 after all.

2022-03-26 18:30 UTC, stgraber commented
@tomponline a quick rebase should clear the tests on this one

2022-03-28 09:42 UTC, monstermunchkin requested changes

2022-03-28 09:42 UTC, monstermunchkin commented on shared/util.go
> +	if _, found := m[key]; found {
Lets split this to be consistent.

2022-03-28 09:57 UTC, tomponline commented on shared/util.go
> +	if _, found := m[key]; found {
Fixed.

2022-03-28 10:29 UTC, monstermunchkin approved these changes

2022-03-28 14:17 UTC, merged