Fix typo in notes
lxc/lxd pull request #10170
Opened 2022-04-01 12:28 UTC by 745150400

2022-04-01 12:33 UTC, tomponline commented on lxd/endpoints/cluster.go
> +// ClusterAddress returns the cluster addresses of the cluster endpoint, or an
This should be just "address"

2022-04-01 12:35 UTC, tomponline commented on lxd/api.go
> +// Get the supported API endpoints
As this is used in the API docs we'll also need a separate commit after regenerating the API docs using `make update-api`, e.g. https://github.com/lxc/lxd/commit/77221976f405246b318af386baa244d4d87f1737

2022-04-01 12:35 UTC, tomponline requested changes
Thanks! A couple of small requests, then good to go :)

2022-04-01 23:58 UTC, stgraber commented
jenkins: test this please

2022-04-02 15:42 UTC, stgraber commented
jenkins: test this please

2022-04-02 21:14 UTC, merged

2022-04-02 21:14 UTC, stgraber commented
Thanks!