lxd/storage/drivers/btrfs: Fix optimized refresh
lxc/lxd pull request #10192
Opened 2022-04-06 12:36 UTC by monstermunchkin

2022-04-06 12:41 UTC, tomponline commented
@monstermunchkin please can you update the tests to check for the failure scenario that was occurring before this fix, so that we can detect regressions in the future, as it seems there is a gap in the test suite that allowed this to be released.

2022-04-06 12:47 UTC, tomponline commented
@monstermunchkin it would be good to add the tests first to recreate the error and then add the fix commits to this PR so we can see it resolve it.

2022-04-06 13:40 UTC, tomponline commented on test/suites/migration.sh
> +  if [ "${lxd_backend}" = "btrfs" ] && [ "${lxd2_backend}" = "btrfs" ] || [ "${lxd_backend}" = "zfs" ] && [ "${lxd2_backend}" = "zfs" ]; then
Why dont we do this test for all storage types (I realise only the btrfs and zfs ones will do optimized transfers, but would also test cross-remote copies for all storage drivers right) ?

2022-04-06 13:41 UTC, tomponline commented on test/suites/migration.sh
> +    lxc_remote copy l1:c1 l2:c1
Suggest also starting the instance after copied to check it starts, and adding a file inside it to check that got copied to prove the copy process is working.

2022-04-06 21:10 UTC, stgraber commented
@monstermunchkin the btrfs tests are failing

2022-04-07 11:18 UTC, monstermunchkin commented
> @monstermunchkin the btrfs tests are failing

I'm working on it.

2022-04-07 13:30 UTC, tomponline commented
@monstermunchkin given that the test suite has passed but there is no ZFS fix in this PR yet, it seems like the test suite is not yet testing for the ZFS failure scenario just yet.

2022-04-07 13:30 UTC, tomponline requested changes
Lets see the tests failing for ZFS before the fix goes in so we can be sure its thoroughly testing the failure scenario.

2022-04-07 14:38 UTC, monstermunchkin commented on lxd/storage/drivers/driver_btrfs_volumes.go
> +	type copyOp struct {
This is btrfs specific.

2022-04-07 16:29 UTC, merged