Database Refactor: Remove UsedBy/Config from Projects
lxc/lxd pull request #10225
Opened 2022-04-11 19:51 UTC by masnax

This adds the last chunk of changes needed for the v2 generator, and is currently in use by `Projects`.

* Removes `UsedBy` and `Config` fields from `db.Project`. 
* Moves `db/projects.go` to use the `version=2` generator.
* Updates generator to support a `references` key, allowing for generation of `Config` and `Devices` methods on each entity.
* Adds generated `GetProjectConfig` and `CreateProjectConfig` methods, generated as part of `GetMany` and `Create` generator comments, specified via `references=Config`.
* Updates `project.ToAPI()` to accept a transaction argument to fill the config field. 
* Uses `api.Project` or explicitly passing in the config type `map[string]string` where we need to access the config.

Probably some more efficiency bits to add here (like a cleaner way to check if a project is used by anything at all, rather than getting the whole list.

2022-04-11 20:44 UTC, masnax commented
@markylaing The changes to `lxd/db/generate/db/method_v2.go` are likely going to be the final form of ClusterTx method generation for the db generator. We will likely want to avoid using anything in `method.go` and instead use `v2` going forward.

2022-04-12 20:29 UTC, tomponline commented
@masnax unit tests are failing im afraid

2022-04-12 22:05 UTC, masnax commented
@tomponline sorry about that, just a stubborn file that I deleted, which got resurrected by a rebase :)

2022-04-13 00:41 UTC, tomponline commented on lxd/api_project.go
> +	images, err := tx.GetImageURIs(db.ImageFilter{Project: &project.Name})
can you add a blank line between each stanza please

2022-04-13 00:43 UTC, tomponline commented on lxd/device/proxy.go
> +					var err error
dont need this line

2022-04-13 00:45 UTC, tomponline commented on lxd/images.go
> +		for _, project := range dbProjects {
van you use make here to preallocate a slice of the needed capacity

2022-04-13 00:48 UTC, tomponline commented on lxd/instance_snapshot.go
> +		err = project.AllowSnapshotCreation(tx, proj)
blank line needed

2022-04-13 00:49 UTC, tomponline commented on lxd/instances_post.go
> +	petname "github.com/dustinkirkland/golang-petname"
this looks like an unrelated change

2022-04-13 00:49 UTC, tomponline commented on lxd/network/driver_ovn.go
> +		var err error
no need for this line

2022-04-13 00:52 UTC, tomponline commented on lxd/network/driver_ovn.go
> +			var err error
no need for this line

2022-04-13 00:52 UTC, tomponline commented on lxd/network/driver_ovn.go
> +		n.state.Cluster.Transaction(func(tx *db.ClusterTx) error {
no err caught here

2022-04-13 00:54 UTC, tomponline commented on lxd/project/project.go
> +		var err error
no need for this line

2022-04-13 00:54 UTC, tomponline commented on lxd/project/project.go
> +		var err error
no need for this line

2022-04-13 00:55 UTC, tomponline commented on lxd/storage_volumes_snapshot.go
>  		return err
blank line

2022-04-13 01:01 UTC, tomponline commented on lxd/api_project.go
> +		if len(project.UsedBy) > 1 || !strings.Contains(project.UsedBy[0], "/profiles/default") {
whats the chrck for default about here? needs a commemt.

2022-04-13 01:03 UTC, tomponline commented on lxd/device/proxy.go
> +				d.state.Cluster.Transaction(func(tx *db.ClusterTx) error {
err not caught

2022-04-13 01:04 UTC, tomponline commented on lxd/network/driver_ovn.go
> +	n.state.Cluster.Transaction(func(tx *db.ClusterTx) error {
err not caught

2022-04-13 01:05 UTC, tomponline commented on lxd/network/driver_ovn.go
> +	n.state.Cluster.Transaction(func(tx *db.ClusterTx) error {
err not caught

2022-04-13 01:05 UTC, tomponline commented on lxd/network/driver_ovn.go
> +		var err error
line not needed

2022-04-13 01:05 UTC, tomponline commented on lxd/network/zone/load.go
> +		return err
blank line

2022-04-13 01:06 UTC, tomponline commented on lxd/network/driver_ovn.go
> +		return err
blank line

2022-04-13 01:06 UTC, tomponline commented on lxd/network/driver_ovn.go
> +		return err
blank line

2022-04-13 01:06 UTC, tomponline commented on lxd/instances_post.go
> +				return err
blank line

2022-04-13 01:07 UTC, tomponline commented on lxd/images.go
> +			return err
blank line

2022-04-13 01:07 UTC, tomponline commented on lxd/images.go
> +			return err
blank line

2022-04-13 01:07 UTC, tomponline commented on lxd/device/disk.go
> +			return err
blank line

2022-04-13 01:08 UTC, tomponline commented on lxd/backup.go
> +			return err
blank line

2022-04-13 01:08 UTC, tomponline commented on lxd/project/project.go
> +		return err
blank line

2022-04-13 01:09 UTC, tomponline commented on lxd/project/project.go
> +		return err
blank line

2022-04-13 01:09 UTC, tomponline commented on lxd/project/project.go
> +		return err
bl

2022-04-13 01:10 UTC, tomponline requested changes
looks good. ill make another pass on my pc tomorrow.

2022-04-14 17:20 UTC, stgraber commented
@tomponline what's the state on this one?

2022-04-14 17:36 UTC, tomponline commented
@stgraber waiting for @masnax to make the changes then I'll look again.

2022-04-14 18:45 UTC, masnax commented
@tomponline sorry, forgot to mention the changes have been made. Should be good to go.

2022-04-14 19:12 UTC, tomponline commented
> @tomponline sorry, forgot to mention the changes have been made. Should be good to go.

Cheers, looking now.

2022-04-14 19:14 UTC, tomponline approved these changes
LGTM!

2022-04-14 19:14 UTC, merged