lxd/instance_put: Do not update root device
lxc/lxd pull request #10224
Opened 2022-04-11 19:22 UTC by monstermunchkin

When updating an instance, the root device was updated as well. This
caused problems when doing migration and the names of the source and
target storage pools differed.

This fixes the issue by using not changing the root device.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

2022-04-11 19:25 UTC, tomponline commented
I'm on my phone so might not be seeing the whole picture here, but does this not prevent changing the root disk size?

2022-04-11 19:27 UTC, tomponline commented
> This
> caused problems when doing migration and the names of the source and
> target storage pools differed.

I think you need to identify the root disk device (there's a function for that as it may not be called "root") and then enforce the pool property only.

2022-04-11 19:52 UTC, tomponline reviewed
Do you have an example command that this fixes please?

2022-04-11 19:58 UTC, tomponline requested changes
Please can you add a test for the scenario this fixes which wasn't covered before. Thanks

2022-04-11 19:59 UTC, stgraber commented
This indeed feels wrong. We indeed don't allow modifying the `root` disk pool through `PUT`, instead you need to use `POST` to move the instance to another pool.

But this kind of verification should be done through normal validation in `Update()` and not in the API endpoint.

2022-04-11 19:59 UTC, stgraber commented
As in, this should fail with a validation error:
```
stgraber@dakara:~$ lxc config device override b1 root pool=dir
Device root overridden for b1
stgraber@dakara:~$ 
```

2022-04-11 20:09 UTC, monstermunchkin commented
> Do you have an example command that this fixes please?

```
$ lxc storage create zfs zfs
$ lxc storage create l2:zfs-1 zfs
$ lxc init testimage c1 -s zfs
$ lxc copy c1 l2:c1 -s zfs-1
$ lxc copy c1 l2:c1 --refresh
Error: Failed to load device to add "root": Failed to get storage pool "zfs": Storage pool not found
```

2022-04-11 20:12 UTC, stgraber commented
Right, so again, validation should indeed fail in such cases. For such a refresh case, we'd expect the user to pass `-s zfs-1 --refresh`

2022-04-11 20:37 UTC, monstermunchkin commented
@stgraber Actually, I don't quite agree. Let's say on `l2` the default pool is `zfs-1`. In that case `lxc c1 l2:c1` will copy the instance to `zfs-1` without explicitly needing `-s`. Why should `-s` be enforced when using `--refresh`?

2022-04-11 20:43 UTC, stgraber commented
It wouldn't be.

If you copy from l1 to l2 with a default profile pointing to a different pool, that's all fine, your local config never mention the wrong pool. Where you do need to specify it every time is if you want it on a different pool than what you'd normally get in the expanded devices.

2022-04-11 20:45 UTC, stgraber commented
So foo going from l1 to l2 with no root device in local config and using the default profile will land on l2 in whatever pool the default profile mentions and refreshes will work fine without having to pass `-s`.

Same goes for an instance which has a pool mentioned in its local config which happens to also exist on the target, all good.

Where `-s` must be specified is if the computed expanded config on the target refers to a pool with doesn't exist or which differs from the pool the instance is currently stored on.

2022-04-12 01:19 UTC, stgraber commented on lxd/instance/drivers/driver_lxc.go
> +	_, reqRootConfig, err := shared.GetRootDiskDevice(args.Devices.CloneNative())
args.Devices is equivalent to `d.localDevices`, this seems wrong.

2022-04-12 02:40 UTC, stgraber commented
I've pushed a simplified version of this which runs the check after validating the config and devices already, so saving us from a bunch of checking and error handling as we know we'll be dealing with normal looking devices.

It's also limited to user requested changes so it won't break the few cases where LXD may need to do an update itself.

2022-04-12 04:52 UTC, merged

2022-04-12 09:03 UTC, tomponline reviewed
Thanks for the tests.