Tiny lint fixes
lxc/lxd pull request #10619
Opened 2022-06-29 19:09 UTC by simondeziel

Address the feedback left in #10617 after it was merged and a few more things.

2022-06-29 19:14 UTC, tomponline commented on test/lint/negated-is-bool.sh
> +OUT=$(git grep -P '!(shared\.)?Is(True|False).*\(' '*.go' || true)
Does git grep work also on uncommitted files? If not I think we should stop using it for these static analysis checks as it should work on uncommitted files when run locally.

2022-06-29 19:15 UTC, tomponline commented on test/lint/newline-after-block.sh
> +files=$(git ls-files "*.go")
AFAIK this doesn't include uncommitted files, if that is the case, then I don't think we want this change as running `make static-analysis` should work on uncommitted files.

2022-06-29 19:17 UTC, tomponline requested changes
I think we need to check and make sure that running `make static-analysis` works the same for uncommitted files as it does for committed files.

2022-06-29 19:20 UTC, tomponline commented
@markylaing the tests workflow is always failing the unit tests on TestConvertNetworkConfig btw.

2022-06-29 19:55 UTC, markylaing commented
> @markylaing the tests workflow is always failing the unit tests on TestConvertNetworkConfig btw.

@tomponline ah I see, GitHub actions stopped working when I added unit tests. I should have put it back to draft to make sure. Not sure why it is failing but we can remove the unit tests and reinstate unit tests for the client on Ubuntu in the meantime.

2022-06-29 19:57 UTC, tomponline commented
> > @markylaing the tests workflow is always failing the unit tests on TestConvertNetworkConfig btw.
> 
> @tomponline ah I see, GitHub actions stopped working when I added unit tests. I should have put it back to draft to make sure. Not sure why it is failing but we can remove the unit tests and reinstate unit tests for the client on Ubuntu in the meantime.

Ok thanks that would be good. I'm sure I've seen that failure locally too in the past so hopefully easy to reproduce.

2022-06-29 21:32 UTC, merged

2022-06-30 08:18 UTC, markylaing commented
@tomponline I've removed the unit tests in #10621 - it should pass static analysis now.