lxd/apparmor: apparmor profile for qemu-img
lxc/lxd pull request #10690
Opened 2022-07-24 15:29 UTC by Viktor-Yakovchuk

Hi, this is first step to cover qemu-img calls with apparmor.
Only one call is currently covered: `rlimit --cpu=2 --as=1000000000 qemu-img info -f qcow2 --output=json /var/lib/lxd/images/zxy.rootfs`
It is triggered by `lxc launch images:ubuntu/20.04 vm1 --vm`

I appreciate any comment or reviews.

issue #10253

2022-08-01 17:13 UTC, Viktor-Yakovchuk commented
I have covered all direct qemu-img calls.
But there is the function: [DetectCompressionFile](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/shared/archive.go#L25) that can return qemu-img as a decoder.
It`s references can not use qemu-img:

- [lxc/image.go#L810](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxc/image.go#L810), [lxd/images.go#L3600](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/images.go#L3600) and [lxd/images.go#L3616](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/images.go#L3616) the return value is not used

- [lxd/storage/drivers/generic_vfs.go#L797](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/storage/drivers/generic_vfs.go#L797)  call leads to `err = archive.ExtractWithFds("tar", args, allowedCmds, ioutil.NopCloser(r), sysOS, f)` so qemu-img is not used 

- [lxd/archive/archive.go#L141](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/archive/archive.go#L141) after getting return value there is the check if it is tar or squashfs

- [lxd/backup/backup_utils.go#L21](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/backup/backup_utils.go#L21), [lxd/storage/drivers/driver_btrfs_volumes.go#L174](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/storage/drivers/driver_btrfs_volumes.go#L174) and [lxd/storage/drivers/driver_zfs_volumes.go#L383](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/storage/drivers/driver_zfs_volumes.go#L383) calls leads to CompressedTarReader handler where final call is covered by archive apparmor profile

- [lxd/instances_post.go#L685](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/instances_post.go#L685) and [lxd/storage_volumes.go#L1815](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/storage_volumes.go#L1815) extraction can be called only if DetectCompressionFile return ".squashfs"

The only call where I have uncertainty is [lxd/images.go#L1165](https://github.com/lxc/lxd/blob/08b0e7c448ad7da60c90b8bba889d58b401d4754/lxd/images.go#L1165) I have triggered it by `lxc image import image_file_name remote_name:` and it used gzip (not qemu-img) but I am not sure it is the only one possible way of tiggered this code.

2022-08-03 10:49 UTC, Viktor-Yakovchuk commented
@stgraber Could you please launch tests and take a review?

2022-08-03 11:07 UTC, tomponline commented
@Viktor-Yakovchuk I will try and look at this soon. The jenkins tests don't test VMs so apart from catching container regressions they won't be much use I'm afraid.

2022-08-22 15:36 UTC, tomponline commented
Hi, this is still on my todo list but I am busy with roadmap work at the moment.

2022-09-21 16:53 UTC, stgraber commented
@tomponline we should try to get this merged next week so we have the entire LXD 5.7 cycle to see if anything breaks

2022-09-21 17:09 UTC, tomponline commented
Yep will take a look at this next (and try it out)

2022-09-26 14:48 UTC, tomponline commented on lxd/storage/utils.go
>  		// Use prlimit because qemu-img can consume considerable RAM & CPU time if fed a maliciously
Please can you move the comment here into `RunQemuImgWithApparmor` so its kept with the actual call to `prlimit`.

2022-09-26 14:50 UTC, tomponline commented on lxd/apparmor/qemuimg.go
> +func runQemuImgWithApparmor(cmd string, args []string, stdin io.ReadCloser, sysOS *sys.OS, imgPath string) (string, error) {
The `WithApparmor` is implicit given its in the `apparmor` package, so can just be `QemuImg()` I think.

2022-09-26 14:51 UTC, tomponline commented on lxd/apparmor/qemuimg.go
> +		return "", fmt.Errorf("Failed to start extract: Failed running: tar: %w", err)
tar?

2022-09-26 16:03 UTC, tomponline commented
Please rebase this into a single logical commit rather than showing your iterations.

2022-09-27 10:01 UTC, tomponline commented on lxd/apparmor/qemuimg.go
> +func RunQemuImgWithApparmor(sysOS *sys.OS, cmd []string, imgPath string, dstPath string) (string, error) {
Why 2 functions `runQemuImgWithApparmor` and `RunQemuImgWithApparmor`?

2022-09-27 10:07 UTC, tomponline commented on lxd/apparmor/qemuimg.go
> +func runQemuImgWithApparmor(cmd []string, stdin io.ReadCloser, sysOS *sys.OS, imgPath string, dstPath string) (string, error) {
As this function is specific to `qemu-img` I think we should move the prlimit and qemu-img logic inside this function (along with the comment) and then have a struct called `QemuImgOpts` which can be used to pass the run-time invocation options (such as prlimit settings and extraction options).

2022-09-27 10:08 UTC, tomponline requested changes
Thanks for this! I made some comments. 

If don't have time, let me know and I can take over this PR.

Thanks :)

2022-10-03 10:23 UTC, tomponline commented
jenkins: test this please

2022-10-03 10:24 UTC, tomponline approved these changes

2022-10-03 10:24 UTC, tomponline commented
Thanks!

2022-10-03 11:55 UTC, merged

2022-10-04 13:20 UTC, Viktor-Yakovchuk commented
Thanks, too!