api: metrics: new metric lxd_cpus
lxc/lxd pull request #10849
Opened 2022-08-25 12:55 UTC by exsver

Added new metric for containers: lxd_cpus - The total number of CPUs.

2022-08-25 16:22 UTC, stgraber requested changes
The current commit should be split into:
  - lxd/cgroup: Add GetEffecticeCPUs
  - lxd/metrics: Add lxd_cpu_effective_total

And adding:
 - api: metrics_cpu_effective_total
 
Which contains the usual changes to doc/api-extensions.md and shared/version/api.go

2022-08-25 16:22 UTC, stgraber commented on lxd/cgroup/abstraction.go
> +// parseCPUSet parse cpuset string and returns the number of CPUs.
`parses a cpuset string`

2022-08-25 16:22 UTC, stgraber commented on lxd/cgroup/abstraction.go
> +		// parse non-range values
`Parse non-range values.`

2022-08-25 16:22 UTC, stgraber commented on lxd/cgroup/abstraction.go
> +		// parse ranges
`Parse ranges (should be made of two elements only).`

2022-08-25 16:22 UTC, stgraber commented on lxd/cgroup/abstraction.go
> +		// should be in range format: 1-4 (two elements only)
Drop, covered by comment above.

2022-08-25 16:22 UTC, stgraber commented on lxd/cgroup/abstraction.go
> +			return -1, fmt.Errorf("Failed parsing %q: invalid format", value)
Invalid range format

2022-08-25 16:22 UTC, stgraber commented on lxd/cgroup/abstraction.go
> +func (cg *CGroup) GetCPUs() (int, error) {
GetEffectiveCPUs

2022-08-25 16:22 UTC, stgraber commented on lxd/metrics/types.go
> +	CPUs:                        "lxd_cpus",
lxd_cpu_effective_total

2022-08-25 17:25 UTC, simondeziel commented
Considering the `lxd_cpu_seconds_total` already contains a `cpu` label, I'm not sure what that new metrics will be used for?

```
lxd_cpu_seconds_total{cpu="0",mode="system",name="smb",project="default",type="container"} 59
lxd_cpu_seconds_total{cpu="0",mode="user",name="smb",project="default",type="container"} 157
```

2022-08-25 17:55 UTC, stgraber commented
@simondeziel that's a good point, you can query the effective CPUs today just by looking at the lxd_cpu_seconds_total count for unique cpu label.

@simondeziel what's the promql query to effectively get the effective CPU count that way?

2022-08-25 19:10 UTC, simondeziel commented
@stgraber I think there is a catch with using `lxd_cpu_seconds_total` though. Here's with my instance on your cluster:

```
count(group(lxd_cpu_seconds_total{name="gw-hdc"}) by (cpu))
```

This gives me `32` while there is only 1 CPU core accessible to the instance (as reported by `nproc`). Now if I tell it to ignore CPUs without any time spent:

```
count(group(lxd_cpu_seconds_total{name="gw-hdc"} > 0) by (cpu))
```

I get `8`, presumably because there is no CPU pinning going on.

### Prometheus Node Exporter

It does essentially the same as the first query as we can see in those record rules (https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/rules/rules.libsonnet):

```
count without (cpu, mode) (
                node_cpu_seconds_total{%(nodeExporterSelector)s,mode="idle"}
              )
```

Translated for LXD we'd get:

```
count without (cpu, mode) (lxd_cpu_seconds_total{name="gw-hdc", mode="system"})
```

Which gives me `32`, again.

@stgraber could you check if my numbers for the `gw-hdc` container match what's in the cpuset file on `abydos`?

2022-08-25 19:47 UTC, stgraber commented
```
root@abydos:~# cat /sys/fs/cgroup/cpuset/lxc.payload.sdeziel_gw-hdc/cpuset.effective_cpus 
18
```

So single CPU pinned on that one.

2022-08-25 19:59 UTC, simondeziel commented
@stgraber that's odd, I'm now getting result for CPU 18 only but 2 hours ago, the container had touched a bunch of CPUs. Here's what I had:

```
lxd_cpu_seconds_total{name="gw-hdc"} offset 2h > 0
```
|Metric|Value|
|--------|--------|
lxd_cpu_seconds_total{cpu="10", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 4
lxd_cpu_seconds_total{cpu="10", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 13
lxd_cpu_seconds_total{cpu="13", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 9
lxd_cpu_seconds_total{cpu="13", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 21
lxd_cpu_seconds_total{cpu="15", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 11
lxd_cpu_seconds_total{cpu="15", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 23
lxd_cpu_seconds_total{cpu="18", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 9
lxd_cpu_seconds_total{cpu="18", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 22
lxd_cpu_seconds_total{cpu="20", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 10
lxd_cpu_seconds_total{cpu="20", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 22
lxd_cpu_seconds_total{cpu="22", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 17
lxd_cpu_seconds_total{cpu="22", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 39
lxd_cpu_seconds_total{cpu="6", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 1
lxd_cpu_seconds_total{cpu="6", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 6
lxd_cpu_seconds_total{cpu="7", instance="abydos", job="lxd-abydos", mode="system", name="gw-hdc", project="sdeziel", type="container"} | 3
|lxd_cpu_seconds_total{cpu="7", instance="abydos", job="lxd-abydos", mode="user", name="gw-hdc", project="sdeziel", type="container"} | 7|

2022-08-25 20:12 UTC, exsver commented on lxd/cgroup/abstraction.go
> +// parseCPUSet parse cpuset string and returns the number of CPUs.
Done

2022-08-25 20:12 UTC, exsver commented on lxd/cgroup/abstraction.go
> +		// parse non-range values
Done

2022-08-25 20:21 UTC, exsver commented
cgroup v2:

<pre>
# cat /sys/fs/cgroup/lxc.payload.ct1003/cpuset.cpus.effective 
0-1
</pre>

<pre>
# lxc query -X GET --wait /1.0/metrics
# HELP lxd_cpu_seconds_total The total number of CPU seconds used in milliseconds.
# TYPE lxd_cpu_seconds_total counter
lxd_cpu_seconds_total{cpu="0",mode="system",name="ct1003",project="default",type="container"} 54
lxd_cpu_seconds_total{cpu="0",mode="user",name="ct1003",project="default",type="container"} 111
# HELP lxd_disk_read_bytes_total The total number of bytes read.
# TYPE lxd_disk_read_bytes_total counter
...
</pre>

<pre>
# lxc exec ct1003 lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1

</pre>

2022-08-25 20:57 UTC, stgraber commented
@simondeziel that's likely because things got re-balanced by LXD.

2022-08-26 00:52 UTC, stgraber commented
So based on above (LXD re-balancing), would you agree this change makes sense then?

@simondeziel

2022-08-26 14:45 UTC, simondeziel commented
Cgroupv2 doesn't split CPU usage per CPU so the LXD code reports all usage as being on cpu="0" (https://github.com/lxc/lxd/blob/master/lxd/cgroup/abstraction.go#L340), thanks @stgraber for the walk-through.

As such, I think it makes sense to include that new metric. Thanks @exsver for proposing it!

2022-08-28 16:32 UTC, merged