Export initialization helpers
lxc/lxd pull request #11036
Opened 2022-10-18 20:13 UTC by masnax

This exports some helpers to make it easy to initialize LXD from a `go` application. These helpers were initially under the `main` package, so I've moved the `node` related helpers to the `node` package, and moved `ClusterMemberJoinTokenDecode` to the cluster package.

This will be particularly helpful in bootstrapping LXD for MicroCloud, reducing code duplication.

2022-10-18 20:25 UTC, tomponline commented
Hrm. I can see why this would be useful. But we need to be careful that we dont start to confuse what is our external api stability commitment with internal api structs which can change  more freely. There is also a plan to eventually move much of what is internal to lxd into an internal subdir to prevent cross application imports such as this.

It sounds like we need to move these structs and helpers into the shared/api package, if we are effectively making them an external api other apps will depend on.

Please can you explain further why you need this? Thanks

2022-10-18 20:29 UTC, tomponline requested changes
I think that these structs and helpers need to be in shared package if we are providing them as an external api to other applications. We dont encourage other apps to import packages from lxd/lxd... as may change without notice.

2022-10-18 20:30 UTC, masnax commented
@tomponline for MicroCloud, we will want to bootstrap LXD on an uninitialized system (and then enable clustering, but that's already a public API). To set up default config/network/storage/profiles/projects, I would have to either fully duplicate these helpers on the MicroCloud side, or export them. I figured having LXD handle the source of truth for what is a valid initialization made the most sense.

2022-10-18 20:32 UTC, tomponline commented on lxd/cluster/connect.go
> +func JoinTokenDecode(input string) (*api.ClusterMemberJoinToken, error) {
Let's move this into a shared package

2022-10-18 20:35 UTC, tomponline commented
> @tomponline for MicroCloud, we will want to bootstrap LXD on an uninitialized system (and then enable clustering, but that's already a public API). To set up default config/network/storage/profiles/projects, I would have to either fully duplicate these helpers on the MicroCloud side, or export them. I figured having LXD handle the source of truth for what is a valid initialization made the most sense.

Is there a reason micro cloud is not interacting with the "lxd" command  and providing a preseed file?

2022-10-18 20:37 UTC, masnax commented
> > @tomponline for MicroCloud, we will want to bootstrap LXD on an uninitialized system (and then enable clustering, but that's already a public API). To set up default config/network/storage/profiles/projects, I would have to either fully duplicate these helpers on the MicroCloud side, or export them. I figured having LXD handle the source of truth for what is a valid initialization made the most sense.
> 
> Is there a reason micro cloud is not interacting with the "lxd" command and providing a preseed file?

Wouldn't interacting with the CLI also be prone to change?

2022-10-18 20:49 UTC, tomponline commented
> > > @tomponline for MicroCloud, we will want to bootstrap LXD on an uninitialized system (and then enable clustering, but that's already a public API). To set up default config/network/storage/profiles/projects, I would have to either fully duplicate these helpers on the MicroCloud side, or export them. I figured having LXD handle the source of truth for what is a valid initialization made the most sense.
> > 
> > 
> > Is there a reason micro cloud is not interacting with the "lxd" command and providing a preseed file?
> 
> Wouldn't interacting with the CLI also be prone to change?

Yes. The lxd init command and preseed file format is effectively our api boundary at the moment. With no changes required for micro cloud to use it.

Ive got no problem with also providing those api structs but we need to make sure its clear they are part of our api (so being in shared/api) so changes to them fall under the usual api change rules.

2022-10-18 20:52 UTC, tomponline commented
@masnax basically if you ever find yourself importing packages from lxd/lxd... outside of the lxd then its a red flag.

2022-10-18 20:53 UTC, masnax commented
> @masnax basically if you ever find yourself importing packages from lxd/lxd... outside of the lxd then its a red flag.

Good to know :)

2022-10-18 20:54 UTC, masnax commented
@tomponline I've moved the helpers to the `shared` package (the init helpers needed their own package thanks to import cycles). 

Any idea what these errors are about though? They seem to be otherwise unrelated to the changes here...

2022-10-18 21:00 UTC, masnax commented
Oh I see, `lxd/projects` imports the `db` package.

2022-10-18 21:06 UTC, tomponline commented
> Oh I see, `lxd/projects` imports the `db` package.

We can't have anything in shared import db packages.

2022-10-19 12:10 UTC, tomponline commented
@masnax I've had a chance to take a look at this more closely (now not on my phone):

- The `lxd init` command is currently the "API" that people/systems use to initialise LXD. This command can take a preseed file. However the preseed file format is not currently defined via exported structs that integrating systems can use to marshal to the required YAML required for the `lxd init` command.
- So I think it makes sense to provide structs in `shared/api` for use generating the `lxd init` preseed file. As effectively this is a supported API via the `lxd init` command that we expect user/systems that integrate with LXD to use.
- I'm not sure these structs should mention "internal" as they aren't really internal, but instead represent the preseed format.
- As for external systems interfacing directly with the `/internal` API endpoint, I'm not sure about that. The `/internal` endpoint is supposed to be only for `lxd` itself to use (hence the name).
- If we want external systems to be able to initialise LXD via an API (rather than calling `lxd init`) then I'm thinking we need a new API endpoint prefix (maybe `/init`) for this usage.

What do you think @stgraber 

@masnax in the meantime, would you be able to use the exported structs to generate a preseed file and call `lxd init` directly?

2022-10-19 14:29 UTC, masnax commented
Other than that, I'm fine with introducing an `/init` endpoint if you think that's best.

2022-10-19 14:35 UTC, tomponline commented
@masnax I think it would help me understand if you explain what microcloud is going to request of LXD to initialise it?

One of the structs that was exported originally had the comment "// A request for the /internal/cluster/accept endpoint." which is what gave me that impression.

I'm also not clear why, once the preseed structs are exported, why microcloud isn't going to just feed it to `lxd init`?

That way any future changes to `lxd init`'s preseed apply implementation won't have to be duplicated for microcloud.

2022-10-19 15:13 UTC, masnax commented
@tomponline I've dropped the commit exporting the node init helper and struct. 

As we discussed, I'll try to add a formal preseed struct under `shared/api` and we can discuss with @stgraber about adding an `/init` endpoint.

2022-10-19 15:18 UTC, tomponline approved these changes

2022-10-19 18:41 UTC, tomponline approved these changes

2022-10-19 18:41 UTC, merged