merge the instance type of local file and website
lxc/lxd pull request #11077
Opened 2022-11-01 12:22 UTC by ichiro999

We have some customized instance types,  so want to  merge the instance type of local file  and website, rather than directly overwrite

2022-11-01 15:53 UTC, stgraber commented
Hmm, I think I'd prefer allowing a separate file and merging the two together rather than always merging what comes from the website. The reason for that being that we should be able to remove instance type names should a cloud deprecate/remove them.

2022-11-02 01:32 UTC, ichiro999 commented
> 
thank，your mind is to merge the content of instance_type.yaml with the content of your site.

2022-11-16 14:12 UTC, tomponline commented on lxd/instance_instance_types.go
> +func instanceLoadFromWebsite(ctx context.Context, d *Daemon) map[string]map[string]*instanceType {
This function should still return an error.

2022-11-16 14:12 UTC, tomponline commented on lxd/instance_instance_types.go
> +func instanceLoadFromWebsite(ctx context.Context, d *Daemon) map[string]map[string]*instanceType {
And a nil map if an error occurs.

2022-11-16 14:18 UTC, tomponline commented
> 

I think @stgraber means that the custom instance types should not be stored in the `shared.CachePath("instance_types.yaml")` file as this is supposed to just be a cache of the instance types from the web site.

Any custom types should be read from a separate file and then merged in memory when loading.

2022-11-26 04:11 UTC, ichiro999 commented
> > 
> 
> I think @stgraber means that the custom instance types should not be stored in the `shared.CachePath("instance_types.yaml")` file as this is supposed to just be a cache of the instance types from the web site.
> 
> Any custom types should be read from a separate file and then merged in memory when loading.

2022-11-26 04:16 UTC, ichiro999 commented
> comments

@tomponline thx, it mean that we should provide a directory for customized intsnace type, and "instance_types.yaml" and website is used for default type，lxd merge them to member？

2022-12-06 09:04 UTC, tomponline commented on lxd/instance_instance_types.go
> +			defaultAddr := "images.linuxcontainers.org"
Lets make this a constant at the top of the file called `imagesDomain`

2022-12-06 09:05 UTC, tomponline commented on lxd/instance_instance_types.go
> +	sort.Slice(entries, func(i, j int) bool {
Newline between each stanza please

2022-12-06 09:05 UTC, tomponline commented on lxd/instance_instance_types.go
> +			logger.Error("read instance types from file error", logger.Ctx{"err": err, "file": entry.Name()})
Log messages should start with upper case letter

2022-12-06 09:07 UTC, tomponline commented on lxd/instance_instance_types.go
> +	sort.Slice(entries, func(i, j int) bool {
Why are you sorting entries? This should have a comment if its important, so the knowledge is retained. Thanks

2022-12-06 09:08 UTC, tomponline commented on shared/util.go
> -	logDir := "/var/cache/lxd"
Good catch though! :)

2022-12-06 09:08 UTC, tomponline commented on lxd/instance_instance_types.go
> -
Leave this please

2022-12-06 09:25 UTC, tomponline requested changes
I have concerns around the file based approach we are thinking of taking here as it doesn't work like pretty much all other config (which is stored in a database) and thus introduces problems with config distribution in a clustered environment.

Additionally not all of your commits are signed off (which is required, see https://github.com/lxc/lxd/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) and the PR needs to be rebased and structured into logical commits, see https://github.com/lxc/lxd/blob/master/CONTRIBUTING.md#commit-structure

Thanks

2023-03-16 19:43 UTC, stgraber commented
Going to take over this one quickly to get it into a usable state for 5.12

2023-03-16 19:47 UTC, stgraber commented
Actually, I can't do that as this is not signed-off at all, so it's not just a commit missing it but both commits have it missing.
Going to be closing this for inactivity then as this hasn't been touched since December.

2023-03-16 19:47 UTC, closed without merging