lxd/device/tpm: Expose tpmrm to the container
lxc/lxd pull request #11139
Opened 2022-11-21 17:37 UTC by xnox

This fixes #11138.

2022-11-21 18:01 UTC, tomponline commented on lxd/device/tpm.go
What are these numbers? Can we define them as constants? Or comment to explain what the logic is doing here for future readers?

2022-11-21 18:02 UTC, tomponline commented on lxd/device/tpm.go
> +		rules["pathrm"] = validate.Optional(validate.IsNotEmpty)
What is "rm" and can it always be derived from path? Do we need a new setting for it?

2022-11-21 18:05 UTC, tomponline requested changes
From looking at the linked issue "rm" in this context appears to mean Resource Manager. It would be good to make this clearer in the code by way of comments to make it less opaque for future readers. Maybe something along the lines of describing what a resource manager is and when it is provided by the kernel? Thanks

2022-11-21 18:06 UTC, tomponline commented on lxd/device/tpm.go
> +	err = unixDeviceSetupCharNum(d.state, d.inst.DevicesPath(), "unix", d.name, d.config, uint32(major), uint32(minorRM), d.config["pathrm"], false, &runConf)
I think this lack of empty line between blocks will fail our static analysis

2022-11-21 18:32 UTC, xnox commented
> From looking at the linked issue "rm" in this context appears to mean Resource Manager. It would be good to make this clearer in the code by way of comments to make it less opaque for future readers. Maybe something along the lines of describing what a resource manager is and when it is provided by the kernel? Thanks

yes RM is resource manager. One can either run tpm2-abrmd themselves, or use kernel provided one. These days there are little difference between the two and most use the kernel provided one by default. Without one, the tpm provided inside the lxd container currently is useless and cannot be used beyond the most simple operations. An operation to create a key requires a resource manager, and normally it's just there and automatically used. Given there isn't one exposed in the containers today, imho the tpm2 inside the container is broken. Running tpm2-abrmd inside the container seems to be very hard / broken, given that `/dev/tpm*` inside the container is not owned by the correct user.

Btw, is there a way to specify desired user/group for chrdevices that lxd is mounting inside the cointainers?

In theory, one can derive tpmrm path from tpm, i.e. on linux host they are normally named as a pair of tpmN and tpmrmN. I don't know why lxd configuration for the containers allows to specify an arbitrary path for the first one. And given it can be an arbitrary path today, there is no way to know what RM path should be for it.

We could replace `path:string` with `devnum:uint` such that users specify `device add mytpm tpm devnum=3` which would then create `/dev/tpm3 /dev/tpmrm3` inside the container.

About numbers.... they really seem to be special/random

https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm-chip.c#L346
https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm2-space.c#L618
https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm.h#L34
https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm.h#L36

devno 0, tpm device minor TPM_MINOR (244), tpmrm device minor DEVNO + TPM_NUM_DEVICES(65536) = 65536
devno 1, tpm device minor DEVNO (1), tpm device minor DEVNO + TPM_NUM_DEVICES(65536) = 65537
devno 2, tpm device minor DEVNO (2), tpm device minor DEVNO + TPM_NUM_DEVICES(65536) = 65538
...

2022-11-21 21:31 UTC, xnox commented
Can Jenkins please be executed on this branch?

2022-11-22 09:56 UTC, tomponline commented
jenkins: test this please

2022-11-22 10:50 UTC, tomponline approved these changes
LGTM, thanks!

2022-11-22 10:52 UTC, tomponline commented
> > From looking at the linked issue "rm" in this context appears to mean Resource Manager. It would be good to make this clearer in the code by way of comments to make it less opaque for future readers. Maybe something along the lines of describing what a resource manager is and when it is provided by the kernel? Thanks
> 
> yes RM is resource manager. One can either run tpm2-abrmd themselves, or use kernel provided one. These days there are little difference between the two and most use the kernel provided one by default. Without one, the tpm provided inside the lxd container currently is useless and cannot be used beyond the most simple operations. An operation to create a key requires a resource manager, and normally it's just there and automatically used. Given there isn't one exposed in the containers today, imho the tpm2 inside the container is broken. Running tpm2-abrmd inside the container seems to be very hard / broken, given that `/dev/tpm*` inside the container is not owned by the correct user.
> 
> Btw, is there a way to specify desired user/group for chrdevices that lxd is mounting inside the cointainers?
> 
> In theory, one can derive tpmrm path from tpm, i.e. on linux host they are normally named as a pair of tpmN and tpmrmN. I don't know why lxd configuration for the containers allows to specify an arbitrary path for the first one. And given it can be an arbitrary path today, there is no way to know what RM path should be for it.
> 
> We could replace `path:string` with `devnum:uint` such that users specify `device add mytpm tpm devnum=3` which would then create `/dev/tpm3 /dev/tpmrm3` inside the container.
> 
> About numbers.... they really seem to be special/random
> 
> https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm-chip.c#L346 https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm2-space.c#L618 https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm.h#L34 https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm.h#L36
> 
> devno 0, tpm device minor TPM_MINOR (244), tpmrm device minor DEVNO + TPM_NUM_DEVICES(65536) = 65536 devno 1, tpm device minor DEVNO (1), tpm device minor DEVNO + TPM_NUM_DEVICES(65536) = 65537 devno 2, tpm device minor DEVNO (2), tpm device minor DEVNO + TPM_NUM_DEVICES(65536) = 65538 ...

Thanks for the explanation :)

2022-11-22 10:52 UTC, merged

2022-11-22 11:15 UTC, xnox commented
> > Btw, is there a way to specify desired user/group for chrdevices that lxd is mounting inside the cointainers?
> 
> We normally have a uid and gid settings on unix devices, e.g. https://linuxcontainers.org/lxd/docs/master/reference/devices_unix_char/#devices-unix-char
> 
> So we probably could do with having those settings on the `tpm` device too (only for containers though).

but that's numeric uids only, unfortunately tss user/group are not globally defined, but are dynamically added inside the container. And thus one has to look up names inside the container to make it work. I have now uploaded tpm-udev package update into lunar to address this in the containers https://launchpad.net/ubuntu/+source/tpm-udev/0.6ubuntu1 by adding tpmfiles.d and .path unit to ensure that dynamically added tpms and those that are available at instance start time have correct permissions.

2022-11-22 11:29 UTC, tomponline commented
LXD doesn't trust what is inside an instance so we do not perform name to uid resolution using the contents of an instance.

2022-11-22 11:31 UTC, tomponline commented
> I have now uploaded tpm-udev package update into lunar to address this in the containers https://launchpad.net/ubuntu/+source/tpm-udev/0.6ubuntu1 by adding tpmfiles.d and .path unit to ensure that dynamically added tpms and those that are available at instance start time have correct permissions.

Thanks!