btrfs: Fix optimized refresh
lxc/lxd pull request #11337
Opened 2023-02-08 08:46 UTC by monstermunchkin

2023-02-14 10:38 UTC, tomponline commented on lxd/storage/backend_lxd.go
> +func (b *lxdBackend) RefreshInstance(inst instance.Instance, src instance.Instance, srcSnapshots []instance.Instance, allowInconsistent bool, snapshots bool, op *operations.Operation) error {
Can we use `srcSnapshots` argument rather than needing a new argument?

2023-02-14 10:43 UTC, tomponline commented on lxd/storage/backend_lxd.go
> +func (b *lxdBackend) RefreshInstance(inst instance.Instance, src instance.Instance, srcSnapshots []instance.Instance, allowInconsistent bool, snapshots bool, op *operations.Operation) error {
Yeah looking at where `RefreshInstance` is called, `srcSnapshots` should be nil in instance only mode. Whereas if there are no snapshots to sync it should be an empty slice I think.

2023-02-14 10:51 UTC, tomponline requested changes
Looks good, just a question around the need for an additional function argument.

2023-02-15 08:01 UTC, tomponline commented
@ru-fu was there any documentation changes we need to make as part of these changes to how btrfs refresh works?

2023-02-15 11:00 UTC, ru-fu commented
> @ru-fu was there any documentation changes we need to make as part of these changes to how btrfs refresh works?

No, I think this was just a bug fix to make btrfs work as intended. The relevant section is here and should be correct as far as I can tell:
https://linuxcontainers.org/lxd/docs/latest/reference/storage_drivers/#optimized-volume-transfer

We'll need a doc update when we switch to using rsync when there are no snapshots.

2023-02-15 11:03 UTC, tomponline commented
> > @ru-fu was there any documentation changes we need to make as part of these changes to how btrfs refresh works?
> 
> No, I think this was just a bug fix to make btrfs work as intended. The relevant section is here and should be correct as far as I can tell: https://linuxcontainers.org/lxd/docs/latest/reference/storage_drivers/#optimized-volume-transfer
> 
> We'll need a doc update when we switch to using rsync when there are no snapshots.

Ah yeah, that is what it was now, thanks.
In that case we do need that for this PR as this commit includes that change https://github.com/lxc/lxd/pull/11337/commits/5e1661066c092bfb945cce7ede4c0bb9052de5e3

2023-02-15 11:08 UTC, ru-fu commented
> Ah yeah, that is what it was now, thanks. In that case we do need that for this PR as this commit includes that change [5e16610](https://github.com/lxc/lxd/commit/5e1661066c092bfb945cce7ede4c0bb9052de5e3)

Is that for Btrfs only? Or for all storage drivers that have optimized transfer?

2023-02-15 11:12 UTC, tomponline commented
> > Ah yeah, that is what it was now, thanks. In that case we do need that for this PR as this commit includes that change [5e16610](https://github.com/lxc/lxd/commit/5e1661066c092bfb945cce7ede4c0bb9052de5e3)
> 
> Is that for Btrfs only? Or for all storage drivers that have optimized transfer?

Thats a good point, we need something similar for ZFS and Ceph @monstermunchkin can you add that to this PR please?

As an aside, when you added optimized refresh, did that include Ceph (does it even support such a concept)?

@ru-fu BTRFS, Ceph and ZFS are the only ones that have an optimized transfer mechanism so they are the only ones that need to fallback to rsync for container-only migrations.

2023-02-15 13:19 UTC, ru-fu commented
Here's my suggestion for the doc update.

Second paragraph:

```
LXD uses this optimized transfer when transferring instances and snapshots between storage pools that use the same storage driver, if the storage driver supports optimized transfer and the optimized transfer is actually quicker.
Otherwise, ...
```

Last paragraph:

```
On the other hand, refreshing copies of instances without snapshots (either because the instance doesn't have any snapshots or because the refresh uses the `--instance-only` flag) would actually be slower than using `rsync`.
In such cases, the optimized transfer would transfer the difference between the (non-existent) latest snapshot and the main volume, thus the full volume.
Therefore, LXD uses `rsync` instead of the optimized transfer for refreshes without snapshots.
```

2023-02-15 15:19 UTC, monstermunchkin commented
> Thats a good point, we need something similar for ZFS and Ceph @monstermunchkin can you add that to this PR please?

> you might want to separate this into two PRs, one to fix the BTRFS optimized refresh, without the fallback to rsync, and the other adding fallback to rsync support for all optimized storage drivers that need it, along with the documentation.

Done and done: https://github.com/lxc/lxd/pull/11368

> As an aside, when you added optimized refresh, did that include Ceph (does it even support such a concept)?

@tomponline No, only btrfs and zfs IIRC.

2023-02-15 15:35 UTC, tomponline approved these changes

2023-02-15 15:43 UTC, tomponline commented
@monstermunchkin out of interest, whats the storage around optimized refresh for ceph?

2023-02-15 15:51 UTC, monstermunchkin commented
> @monstermunchkin out of interest, whats the storage around optimized refresh for ceph?

There's no optimized refresh for ceph. It always always calls `genericVFSCopyVolume` in `RefreshVolume`. I don't know why it wasn't added as it should be possible in theory.

2023-02-15 16:48 UTC, merged