Add required=false option for nic devices with an unavailable parent
lxc/lxd pull request #11596
Opened 2023-04-21 20:52 UTC by jeffreyxie0615

Add required option to nic device interface that defaults to true. This option can be set using lxc network set <network_name> user.required={true/false}

2023-04-23 10:44 UTC, tomponline commented on lxd/device/nic_bridged.go
> +	required := true
Let's use shared.IsTrueOrEmpty() here instead

2023-04-23 10:47 UTC, tomponline requested changes
From what I can sew it looks like if required=false and network is unavailable then device start will progress at normal which will still likely fail (because network is unavailable) so we will need to ensure device nic isnt actually started.

Also static analysis is failing.

2023-04-23 18:02 UTC, jeffreyxie0615 commented
If I'm understanding this correctly, PreStartCheck needs to return an error, but not actually cause the container to shutdown?

2023-04-24 20:18 UTC, tomponline commented
> If I'm understanding this correctly, PreStartCheck needs to return an error, but not actually cause the container to shutdown?

The `disk` device currently has a similar `required` property. And that returns nil for PreStartCheck and Start when the source doesn't exist but required=false. 

See https://github.com/lxc/lxd/blob/master/lxd/device/disk.go#L470

2023-05-15 07:09 UTC, tomponline commented
@jeffreyxie0615 hey, how are you getting on with this?

2023-05-30 15:17 UTC, tomponline commented
@jeffreyxie0615 shall I close this for now?

2023-06-11 03:25 UTC, closed without merging