lxd/storage: Lock concurrent image creation for not optimized storage drivers
lxc/lxd pull request #11784
Opened 2023-06-02 14:35 UTC by roosterfish

Ensures when using a not optimized storage driver like `dir`, that the `qemu-img` command isn't executed concurrently if multiple VMs are going the be created at the same time. See https://github.com/lxc/lxd/issues/11244.

Fixes https://github.com/lxc/lxd/issues/11244

2023-06-02 15:10 UTC, roosterfish commented
I am not sure if we should place the lock already at this position, but putting the lock directly into `lxd/apparmor/qemuimg.go` removes the option to check for optimized/non optimized storage driver by the caller. 
@tomponline any suggestions?

2023-06-02 15:12 UTC, tomponline commented
Hrm, no I dont think we should be doing this. And also using a simple mutex is going to prevent concurrent instance creates on different images and pools. This is too much of a blunt instrument I think.

I'm wondering if we shouldn't instead not be locking at all, but instead making the apparmor profile per invocation.

2023-06-02 15:15 UTC, tomponline commented
But it will require updates to `qemuImgUnload` and `qemuImgDelete` to accept a `dstPath` argument.

2023-06-02 15:17 UTC, tomponline requested changes
Lets not use locks and instead use an AppArmor profile per combination of source and destination paths.

2023-06-02 15:27 UTC, roosterfish commented
I'll look into this, marking the PR as draft in the meantime.

2023-06-05 09:24 UTC, roosterfish commented
I have removed some functions that seemed redundant since both name and path for the apparmor profile are equivalent.

2023-06-05 09:25 UTC, tomponline requested changes
Please can you break this into logical commits. Thanks

2023-06-05 09:44 UTC, roosterfish commented
Thanks for the suggestion @tomponline. I have now split up the changes by package so that each has their own individual commit message with correct prefix.

2023-06-05 10:17 UTC, tomponline approved these changes
LGTM! thanks

2023-06-05 10:19 UTC, tomponline commented
jenkins: test this please

2023-06-05 13:36 UTC, merged