Shared CLI package
lxc/lxd pull request #11798
Opened 2023-06-06 11:18 UTC by markylaing

This PR moves all* CLI related utils into a single package under `shared/cli`. Additionally, some useful generic methods for table rendering and sorting (see https://github.com/canonical/lxd-cloud/pull/291 and https://github.com/canonical/lxd-cloud/pull/292) have also been moved from LXD Cloud into `shared/cli`.

Follow up PRs may use the new method `RenderSlice` to allow the user to specify column sort order precedence via a `--sort` flag or similar.

* There are still some utils in `lxc/utils.go`, but these are not used outside of the `lxc` package.

2023-06-06 11:30 UTC, markylaing commented
@tomponline @stgraber I briefly marked this as draft due to a refactoring error. That's now fixed and this is ready for review again.

2023-06-06 12:33 UTC, tomponline requested changes
Is renaming the `cmd` package to `cli` necessary? I'm wondering what breakages that will cause for users who import the shared package directly. We should try and limit unnecessary changes in the `shared/*` packages in my view.

Also, please can we have a few tests for the new RenderSlice function?

2023-06-06 12:53 UTC, markylaing commented
> Is renaming the `cmd` package to `cli` necessary? I'm wondering what breakages that will cause for users who import the shared package directly. We should try and limit unnecessary changes in the `shared/*` packages in my view.

I renamed the package because all imports of `shared/cmd` were aliased to `cli` - which I thought was a little odd. But no this isn't necessary and I can change it back to `cmd`.

> Also, please can we have a few tests for the new RenderSlice function?

Yep will do.

2023-06-06 13:51 UTC, markylaing commented
> > Is renaming the `cmd` package to `cli` necessary? I'm wondering what breakages that will cause for users who import the shared package directly. We should try and limit unnecessary changes in the `shared/*` packages in my view.
> 
> I renamed the package because all imports of `shared/cmd` were aliased to `cli` - which I thought was a little odd. But no this isn't necessary and I can change it back to `cmd`.

Just adding to this. I'm not sure why this would cause breakages for users unless they update their go mod. If they do update their go mod there are already some changes that can break their code (e.g. moving websocket utils from `shared` to `shared/ws` - I'm updating lxd cloud now to fix this).

2023-06-06 13:56 UTC, tomponline commented
> > > Is renaming the `cmd` package to `cli` necessary? I'm wondering what breakages that will cause for users who import the shared package directly. We should try and limit unnecessary changes in the `shared/*` packages in my view.
> > 
> > 
> > I renamed the package because all imports of `shared/cmd` were aliased to `cli` - which I thought was a little odd. But no this isn't necessary and I can change it back to `cmd`.
> 
> Just adding to this. I'm not sure why this would cause breakages for users unless they update their go mod. If they do update their go mod there are already some changes that can break their code (e.g. moving websocket utils from `shared` to `shared/ws` - I'm updating lxd cloud now to fix this).

Yeah its just *more* changes they need to switch to.

2023-06-06 13:58 UTC, markylaing commented
> Yeah its just _more_ changes they need to switch to.

Yeah that's fair. I'll just leave it as `shared/cmd` :+1:

2023-06-08 16:49 UTC, markylaing commented
@tomponline I've left the name of `shared/cmd` unchanged and added tests for `SortByPrecedence` and `RenderSlice`. It was a little tricky to test `RenderSlice` because it writes to stdout so I'd appreciate any feedback, thanks :smile:

2023-06-08 17:13 UTC, tomponline commented
Thanks I'll take a look

2023-06-09 06:59 UTC, merged

2023-06-09 06:59 UTC, tomponline commented
LGTM!