Bug vsock loading init
lxc/lxd pull request #11807
Opened 2023-06-08 05:33 UTC by Regis-Caelum

Fixes https://github.com/lxc/lxd/issues/11794

## Description:
This pull request addresses the following issues:

- Fixes the loading of the vsock module in the OS struct's init function.
- Modifies the retrieval of the vsock context ID.
- Updates the vsock module loading to occur in the checkFeatures function of qemu.
- Implements a new function, vsockID(), in qemu to retrieve the context ID.

## Changes Made:

- Modified the OS struct's init function to remove the loading of the vsock module.
- Added a new function, checkFeatures(), in qemu to load the vsock module and check if it is available.
- Implemented the vsockID() function in qemu to retrieve the vsock context ID.
- Updated the necessary function calls and references in the codebase to accommodate the changes.

2023-06-09 07:05 UTC, tomponline commented on lxd/instance/drivers/driver_qemu.go
> +	"github.com/kballard/go-shellquote"
Please dont put external imports with the stdlib ones.

2023-06-09 07:05 UTC, tomponline commented on lxd/instance/drivers/driver_qemu.go
> +	"github.com/mdlayher/vsock"
Please dont mix internal imports with external ones.

2023-06-09 07:07 UTC, tomponline commented on lxd/instance/drivers/driver_qemu.go
> +	vsockID, err := vsock.ContextID()
This should be extracted from the features detected at LXD start time, see `info := DriverStatuses()[instancetype.VM].Info` usage.

2023-06-09 07:07 UTC, tomponline commented on lxd/instance/drivers/driver_qemu.go
> +	vsockID, err := vsock.ContextID()
Otherwise we are duplicating logic.

2023-06-09 07:09 UTC, tomponline commented on lxd/instance/drivers/driver_qemu.go
> +	// Check if vhos-vsock is available
This is already done in `qemu.Info()` which will only call `checkFeatures` if it exists. Not needed.

2023-06-09 07:10 UTC, tomponline requested changes
Please sign off commits, see:

https://github.com/lxc/lxd/blob/master/CONTRIBUTING.md

2023-06-15 07:18 UTC, tomponline commented
@Regis-Caelum would you mind if @MusicDin worked on this one?

2023-06-15 07:19 UTC, Regis-Caelum commented
Okay, np

2023-06-15 13:22 UTC, closed without merging