lxd/recover: Use configuration defaults
lxc/lxd pull request #11820
Opened 2023-06-12 11:01 UTC by MusicDin

Extract the defaults generation inside each pool driver's `Create()` function into a separate `PopulateConfig()` function.

On `lxd recover`, the pool's configuration is populated with default values before the configuration gets validated.

Fixes #10862

2023-06-12 11:05 UTC, MusicDin commented
@tomponline

Please check whether:
- [ ] the approach of extracting default configuration from each pool's driver `Create()` function is followed correctly,
- [ ] `PopulateConfig()` function should contain config validation (e.g. is `zfs.pool_name` valid)

In addition, I have avoided changing `config["source"]` to prevent any changes in the current flow of pool's driver `Create()` function.

2023-06-13 07:45 UTC, tomponline commented on lxd/storage/backend_lxd.go
> +	err = b.driver.PopulateConfig()
this should be done inside the driver I think.

2023-06-13 07:46 UTC, tomponline commented on lxd/storage/drivers/driver_btrfs.go
> +// PopulateConfig populates the storage pool's configuration file with the default values.
We would want a separate commit per driver for review clarity.

2023-06-13 07:47 UTC, tomponline commented on lxd/storage/drivers/driver_ceph.go
> +	revert := revert.New()
I think we should be calling FillConfig from inside Create, as it already can modify the config.

2023-06-13 07:49 UTC, tomponline commented
Lets focus on ZFS for now and we can move the logic for generating defaults for the other storage drivers once we've addressed the actual issue we want to with this PR.

2023-06-13 08:36 UTC, tomponline commented
This is looking good!

2023-06-13 12:41 UTC, tomponline commented
jenkins: test this please

2023-06-14 13:58 UTC, tomponline commented
@MusicDin the tests look good for ZFS, do you want to continue extracting out the logic for the other drivers?

2023-06-14 20:26 UTC, MusicDin commented
Yes, I will go one by one, so that it is easier to review the changes. 

Should I also extract the rest of the defaults for the ZFS pool, such as the `size` and potentially `source`?

2023-06-15 07:16 UTC, tomponline commented
> Should I also extract the rest of the defaults for the ZFS pool, such as the `size` and potentially `source`?

Yes please.

2023-06-15 09:09 UTC, MusicDin commented
@tomponline I suppose that validation should not be part of the `FillConfig()` function?

2023-06-15 12:56 UTC, tomponline commented
> @tomponline I suppose that validation should not be part of the `FillConfig()` function?

Which part were you thinking of?

2023-06-15 13:03 UTC, tomponline commented on lxd/storage/drivers/driver_zfs.go
>  			return fmt.Errorf("zfs.pool_name can't point to a dataset when source isn't set")
Ah, no, lets keep validation until after FillConfig has been applied.

2023-06-15 13:49 UTC, MusicDin commented
@tomponline 

Extracted defaults:
- [x] zfs
- [ ] btrfs
- [ ] dir

If there are no comments, I'll do it for the rest (ceph and lvm)

2023-06-15 14:33 UTC, tomponline commented on lxd/api_internal_recover.go
> +				err := pool.Driver().FillConfig()
So the commit ordering is a little odd here, as we are calling `FillConfig` before its been added to the storage interface and drivers. Please can you order the commits logically so they dont use resources before they exist.

Also, just a small nit, but can you end comments with a full stop. Thanks

2023-06-15 14:36 UTC, tomponline requested changes
LGTM, just a couple of small nits.

2023-06-15 15:13 UTC, MusicDin commented
@tomponline 

I have fixed the order of commits and added a full stop at the end of comments.
In addition, I have extracted the defaults for:
- [ ] ceph
- [ ] cephfs
- [ ] cephobject
- [ ] lvm

2023-06-15 18:09 UTC, MusicDin commented
@tomponline To me the tests look OK. Most failed tests are due to `no space left on device`. Only [this one (TestEndpoints_NetworkSocketBasedActivation)](https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/9929/arch=amd64,backend=dir,compiler=golang-1.18,section=standalone/console) actually failed.

Please take another look, and if there are no other comments, I think we can merge this one?

2023-06-15 18:47 UTC, tomponline commented
Please can you rebase on master so you get the new github runner system tests.

2023-06-19 07:43 UTC, tomponline approved these changes
LGTM!

2023-06-19 07:43 UTC, merged