Issue #7274 Proper Support For Moving Between Pools
lxc/lxd pull request #8249
Opened 2020-12-12 06:18 UTC by vpranav5

Modified the following four files: 
lxd/storage/backend_lxd.go
/shared/api/instance.go
/lxc/move.go
/lxd/instance_post.go

Attempted to address the below specifications:

Have MoveInstance function use MigrateInstance and CreateInstanceFromMigration to move the data across, update the DB record as needed and finally delete the source from its storage pool.

Extend api.InstancePost to add a Pool string entry that the client would use to trigger such a server-side move

Update lxc/move.go to use MigrateContainer in the client codebase combined with that new Pool field to trigger it

Update lxd/instance_post.go on the server side to detect that Pool field and trigger the new MoveInstance logic.

2020-12-15 08:56 UTC, tomponline requested changes
Just a general comment initially, please can you run this through go fmt and remove the multiple blank lines thanks.

Have you been able to test this works?

2020-12-17 03:08 UTC, stgraber commented
The commits also need the `Signed-off-by` line added.

2021-01-20 03:25 UTC, stgraber commented
@tomponline I think I reached the end of the API, CLI and easy boilerplate stuff and the only bit missing for this to work is the database handling bits. Can you take over from here and add those? I seem to remember you had some ideas of what would be needed :)

2021-01-20 03:36 UTC, stgraber commented
Testing is as simple as `lxc move a1 --storage blah`.
The API appears to work fine, it validates the instance isn't running but then fails when retrieving the volume config as that depends on database records which don't exist yet.

It looks like we may need to perform the root disk DB modification first. This would involve pulling the instance config, locating an instance-local root disk device if any, if none, adding one and altering the pool property to point to the target pool.
This should get us past the config issue and let us move the volume. Once moved and the source volume deleted, there may still need to be some work on the DB records for the storage volumes themselves (unless that's all handled properly already by the storage functions).

Validating the right behavior on failure (revert of DB record, delete of new volume, making sure not to destroy old volume) is pretty important too.

Testing for this will be trivial at least :)

2021-01-20 10:00 UTC, tomponline commented
@stgraber yep will take this on.

2021-01-20 15:45 UTC, tomponline commented
Will finish this in PR https://github.com/lxc/lxd/pull/8357

2021-01-20 15:45 UTC, closed without merging