Daemon: Shutdown improvements
lxc/lxd pull request #9258
Opened 2021-09-21 10:39 UTC by tomponline

This PR tries to improve the daemon shutdown process with a view to making the clustering tests more reliable.

There doesn't appear (to me at least, based on reading the code) to be clear process as to what should happen (and in which order) to shutdown a member that has been separated from the cluster database.

This PR tries to improve the speed at which a cluster member will shutdown in that scenario by detecting DB access errors and then reacting to them earlier in the process to try and prevent further long waits when trying to access the DB. It also adds in some timeouts that would otherwise have lead to long waits.

Additionally this PR also fixes an issue whereby the storage pools were trying to be unmounted before shutting down any instances.

There is still more to do to make the daemon shutdown process clear and predictable, but hopefully this will be enough for now to improve things.

2021-09-21 17:19 UTC, monstermunchkin requested changes

2021-09-21 17:19 UTC, monstermunchkin commented on lxd/daemon_storage.go
> +			logger.Errorf("Failed getting storage pool names: %v", err)
For consistency, I believe this should be `log.Ctx{"err": err}`.

2021-09-21 17:19 UTC, monstermunchkin commented on lxd/daemon_storage.go
> +				logger.Errorf("Failed loading storage pool %q: %v", poolName, err)
Same as above, this should have `log.Ctx{}`.

2021-09-21 17:19 UTC, monstermunchkin commented on lxd/daemon_storage.go
> +			logger.Errorf("Failed unmounting storage backup volume %q: %v", storageBackups, err)
Also `log.Ctx{}`

2021-09-21 17:19 UTC, monstermunchkin commented on lxd/daemon_storage.go
> +			logger.Errorf("Failed unmounting storage image volume %q: %v", storageImages, err)
Also `log.Ctx{}`

2021-09-21 17:20 UTC, tomponline commented
thanks @monstermunchkin indeed they should, I'm waiting for the jenkins test results and assuming they are good I will integrate those changes in tomorrow.

2021-09-21 18:13 UTC, tomponline commented
@monstermunchkin fixed

2021-09-21 18:15 UTC, tomponline commented
@stgraber this seems to have improved the test suite reliability, and I'll follow up with the actual desired LVM fix for the workaround shortly.

2021-09-21 22:48 UTC, stgraber commented
LVM test is still failing, so not going to merge until it passes :)

2021-09-22 06:32 UTC, tomponline commented
Jenkins test this please

2021-09-22 06:32 UTC, tomponline commented
Jenkins please test this

2021-09-22 06:33 UTC, tomponline commented
jenkjns: test this please

2021-09-22 06:34 UTC, tomponline commented
jenkins: test this please

2021-09-22 06:34 UTC, tomponline commented
Success!

2021-09-22 08:12 UTC, tomponline commented
> LVM test is still failing, so not going to merge until it passes :)

Yes that's fair enough :)

Although this particular PR still has the LVM unmount workaround that is in the main branch.

I started this branch during investigating the fix for the LVM issue (the fix for that is here https://github.com/lxc/lxd/pull/9255) as I wanted to have the tests passing reliably before I reintroduced the LVM issue (and later the fix), for which neither the main branch nor this branch, it seems, qualifies.

However despite all of these fixes being improvements its clear that I've not yet got to the heart of the problem as this branch, although it is more reliable than the main branch currently.

I'm going to close this PR now as I'm just not confident that this doesn't introduce more issues (as I don't yet understand all the intricacies of the clustering role management) and it clear doesn't guarantee a green test run.

The remaining issues all revolve around clustering and role handover not happening when the tests thing they should, but it is intermittent, suggesting that it is dependent on timing. I've also seen that the heartbeat process can delay a cluster role handover during shutdown that is triggered by d.Kill() during shutdown. But I'd need to spend more time on it and given I've spent 2 days already I think I need to get back to the roadmap stuff now.

2021-09-22 08:12 UTC, closed without merging