Generator: Insert into certificates_projects table
lxc/lxd pull request #9318
Opened 2021-09-30 23:09 UTC by masnax

Closes #9317 

Coincidentally, I actually noticed this while working on the generator! The `certificates_projects` table was always updated independently of the `certificates` table. The fix I've put here should take care of the problem for now, until I finalize my reworking of how the generator handles reference tables.

2021-09-30 23:31 UTC, stgraber commented
@masnax 
```
lxd/db/certificates.mapper.go:348:9: c.UpdateCertificatesProjects undefined (type *ClusterTx has no field or method UpdateCertificatesProjects)
```

2021-10-01 08:01 UTC, tomponline commented on lxd/db/certificates.go
> +		return nil
Shouldn't this case either remove all entries for that certificate, or return an error?

2021-10-01 08:02 UTC, tomponline requested changes
See comment about `UpdateCertificateProjects`

2021-10-01 08:04 UTC, tomponline commented
@masnax maybe outside of the scope for this change, but can `c.UpdateCertificateProjects` be altered/moved/reworked so it can be called inside the transaction of the certificate operation that is being done, so that if there is a fault with either the whole change is rolled back?

2021-10-04 17:27 UTC, masnax commented
> @masnax maybe outside of the scope for this change, but can `c.UpdateCertificateProjects` be altered/moved/reworked so it can be called inside the transaction of the certificate operation that is being done, so that if there is a fault with either the whole change is rolled back?

My understanding was that this is already the case? `UpdateCertificateProjects` is a method on `ClusterTx` which represents one cluster transaction.

2021-10-04 17:39 UTC, tomponline commented
> > @masnax maybe outside of the scope for this change, but can `c.UpdateCertificateProjects` be altered/moved/reworked so it can be called inside the transaction of the certificate operation that is being done, so that if there is a fault with either the whole change is rolled back?
> 
> My understanding was that this is already the case? `UpdateCertificateProjects` is a method on `ClusterTx` which represents one cluster transaction.

Indeed it is, I'd read it as `c *Cluster`

2021-10-04 17:40 UTC, tomponline approved these changes

2021-10-04 19:56 UTC, merged