Draft: Allow USB pass through of specific port path
lxc/lxd pull request #9516
Opened 2021-11-10 22:33 UTC by zyga

With the fixes to USB device pass-through, allowing multiple identical
devices to be used inside one virtual machine, users may want to route
specific USB devices to specific instances. This can be done by
following the physical topology of hubs and ports.

The new `portglob` property can be used to optionally match the port
path to a glob. Port path is a sequence of numbers separated with
dashes, with each number representing a port and dash representing
connections between hubs.

This allows adding arbitrary device plugged to a physical port or a
particular hub to a specific instance. The property is supported for
`usb` device type both virtual machines and on containers and for
`unix-hotplug` on containers only.

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@huawei.com>

2021-11-11 19:26 UTC, stgraber commented on doc/instances.md
> +portglob    | string    | -                 | no        | Glob matching to physical USB port
I suspect `port` or `portpath` would be clearer. I don't know how common `glob` is with our users.

I'd also have the description be something like `USB port path (wildcard supported) (e.g. 9/3/1)`

2021-11-11 19:33 UTC, stgraber commented on doc/instances.md
> +
I'd probably rephrase that a bit to provide context, maybe:

```
USB port paths (`portpath`) are represented as a sequent of numbers separated by dashes.
Each number is a physical USB port or a USB hub. For example `1-2-3` represents a device connected on the 3rd port of a USB hub which is itself connected to the 2nd port of a hub that's itself connected to the machine on its 1st port.

Wildcards can be used to select all devices attached to a specific port. `1-2-*` will attach all devices connected to the 2nd port of a USB hub that's directly connected to the machine. `lsusb -tv` can be used to see the entire USB tree.
```

2021-11-11 19:33 UTC, stgraber commented on doc/instances.md
> +portglob    | string    | -                 | no        | Glob matching to physical USB port
Same wrt namingSame wrt naming

2021-11-11 19:35 UTC, stgraber commented
Looks like a pretty useful feature.

From a commit structure, we'd need:
 - api: Add usb_portpath extension (adds to doc/api-extensions.md and shared/version/api.go)
 - doc: Add portpath field to usb and unix-hotplug
 - shared/validate: Add IsGlob
 - lxd/device: Add portpath support

2021-11-11 22:11 UTC, zyga commented
Thanks for the review @stgraber, I'll re-word and split this as suggested.

I've realized that the unix-hotplug code I wrote is buggy, I'd either leave that out OR look at how to reliably find the port mapping from DEVPATH from udev. The problem is that unlike in the easier usb case, the port is hidden somewhere in the path, and we are looking at `/some/very/long/1-2/path/like/this`. It's not immediately clear to me how to approach this without walking sysfs to look at something that is a usb device in the chain.

2021-11-11 22:53 UTC, zyga commented
Oh and for a bit of extra context: Initially I've used bus number and device number but I quickly realized those are useless as they are dynamically allocated and thus entirely unstable.

I wish there was something higher-level, like "always plug this device to VM", where lxd could compute something akin to snap hotplug interfaces, where for _certain_ device types, there's a bit more uniqueness than the port path. In my world, usb/ttl uarts have serial numbers, mbed devices have serial numbers, disks have plenty of identification. I wish we could offer _that_ to users. Still, the port path is a perfectly serviceable compromise as it gets the job done.

2021-11-24 11:26 UTC, tomponline commented
There's some conflicts to resolve on this branch.

2021-11-24 11:26 UTC, tomponline requested changes
@stgraber has requested come changes to the commit structure, and there are some conflicts to resolve.

2021-12-29 15:24 UTC, zyga commented
I lost track of this branch, I'll pick it up shortly.

2021-12-29 17:34 UTC, stgraber commented
Thanks!

2022-05-12 13:08 UTC, tomponline commented
> I lost track of this branch, I'll pick it up shortly.

Any luck with this @zyga ?

2022-05-19 15:03 UTC, tomponline commented
@zyga this needs rebasing please

2022-05-19 15:11 UTC, zyga commented
> @zyga this needs rebasing please

Ack. I will rebase this as soon as I can.
I'm sorry for neglecting this change.

2022-08-18 08:23 UTC, tomponline commented
@stgraber shall we close this?

2022-08-18 13:05 UTC, closed without merging