Cluster server grouping
lxc/lxd pull request #9583
Opened 2021-11-26 15:40 UTC by monstermunchkin

2021-12-08 02:45 UTC, stgraber commented on shared/api/cluster.go
> +type ClusterGroupsPost struct {
This should include `ClusterGroupPut` so we can set the `Description` as well as `Members` at creation time too.

2021-12-08 03:02 UTC, stgraber commented on lxd/api_cluster.go
> +}
That looks quite wrong, only the `Get` operations should use `allowAuthenticated`, otherwise all non-admin users will be able to alter the groups.

2021-12-08 03:15 UTC, stgraber commented on lxd/api_cluster.go
> +		err = d.cluster.Transaction(func(tx *db.ClusterTx) error {
Don't we have an earlier cluster transaction that this could be done in (to avoid a complete separate DB call)?

2021-12-08 03:17 UTC, stgraber commented on client/interfaces.go
> +	GetClusterGroups() ([]api.ClusterGroup, error)
Missing a `GetClusterGroupNames()`

2021-12-08 03:20 UTC, stgraber commented
@monstermunchkin missing changes to doc/projects.md and doc/cluster.md for the new config options on projects and the extension of `scheduler.instance`.

2021-12-08 03:20 UTC, stgraber commented
@tomponline mind taking a quick look at this one too (ideally after @monstermunchkin addressed initial feedback)?

2021-12-08 11:33 UTC, tomponline commented on lxd/db/node.go
> +	rows.Close()
This line should be a separate commit so it can be backported independently of the schema change feature.

2021-12-08 11:37 UTC, tomponline commented on lxd/db/node.go
> +		// Don't fail on a missing table, we need to handle updates
This comment is in the wrong place, it should be 2 lines up in the section that detects the missing table.

2021-12-08 11:42 UTC, tomponline commented on lxd/db/node.go
> +		groups, err = tx.GetClusterGroupsWithNode(n.Name)
I'm confused why we need to populate groups again in this function, when it should have already been populated into the `NodeInfo.Groups` field by the the `nodes()` function, can we not just copy it from the `n.Groups` field?

2021-12-08 11:49 UTC, tomponline commented on lxd/db/cluster.go
> +func (c *ClusterTx) AddNodeToClusterGroup(groupName, nodeName string) error {
Please can you avoid the use of argument compression here, i.e it should be `groupName string, nodeName string` instead. Thanks

2021-12-08 11:50 UTC, tomponline commented on lxd/db/cluster.go
> +func (c *ClusterTx) RemoveNodeFromClusterGroup(groupName, nodeName string) error {
Argument compression here too.

2021-12-08 11:53 UTC, tomponline commented on lxd/db/node.go
> +		if node.Config["scheduler.instance"] == "all" {
Can't this be one if statement?

2021-12-08 12:08 UTC, tomponline commented on lxd/db/node.go
> +		if node.Config["scheduler.instance"] == "all" {
Could these two be blocks be written like this instead (with comments ofc).

```go
if !shared.StringInSlice(group, node.Groups)  {
    if (node.Config["scheduler.instance"] == "all" && group != "") || node.Config["scheduler.instance"] == "group" {
        continue
    }
}
```

2021-12-08 12:11 UTC, tomponline commented on lxd/api_cluster.go
> +	if req.ServerName != "" && strings.HasPrefix(req.ServerName, "@") {
Please can we have a constant for `@` that can be used here and anywhere else there is logic to check it starts with an `@` so we can see A) where the concept is used (as searching for "@" is tricky) B) that it shows to the reader the "@" means "group name prefix" or something like that?

2021-12-08 12:12 UTC, tomponline commented on lxd/api_cluster.go
> +				return fmt.Errorf("Failed to add new node to the default cluster group: %w", err)
We use "member" rather than "node" in user facing errors.

2021-12-08 12:15 UTC, tomponline commented on lxd/api_cluster.go
> +			return response.NotFound(fmt.Errorf("Cluster group '%s' not found", name))
We're quoting strings using `%q` in errors nowadays for new stuff (and replacing them when we see them in older stuff).

2021-12-08 12:18 UTC, tomponline commented on lxd/api_cluster.go
> +				// Note that members who only belong to this group will not be removed from it.
Should we return an error in this scenario rather than silently only partially completing the request?

2021-12-08 12:19 UTC, tomponline commented on lxd/db/cluster.go
> +		return fmt.Errorf("Rename ClusterGroup: %w", err)
Should be "Failed to rename..." or "Failed renaming..." like in `CreateClusterGroup` above for consistency, and similar for the other errors in this function.

2021-12-08 13:14 UTC, tomponline commented on lxd/db/cluster.go
> +			logger.Debugf("Error adding node %q to cluster group: %s",
Line wrapping is a bit odd here.

2021-12-08 13:15 UTC, tomponline requested changes
A few bits and bobs to change, nothing major, other than that looks good.

2021-12-09 03:57 UTC, stgraber commented
jenkins: test this please

2021-12-09 05:06 UTC, merged